### ISSUE TITLE
GBC/GBA vs GBA/NDS slot

### ISSUE THREAD

**Issue by miguel2al** [v1605/open-source-cart-extender#1]
Hi,

I have a question about GBC/GBA slots, what is the difference compared with GBA/NDS?
The link you posted goes to a GBA/NDS instead, but I can't tell any differencies against other options.

Regards!

**Comment by v1605** [comment]
There is a slightly different form factor, in this listing [this listing](https://www.aliexpress.us/item/3256803484963410.html) you can see some more pictures that show small bumps on the bottom of the slot. These bumps align with holes on the PCB to keep it aligned and secure.

To confirm: I believe this one is compatible https://www.aliexpress.us/item/3256802306023288.html

**Comment by miguel2al** [comment]
I printed the linked 3D case but I don't see the bump correspondent wholes in it, but even more bumps (one big and one small), or are slot bumps only for spacing to the case wall instead?

Sorry for being so annoying XD & thanks for the quick response.

**Comment by miguel2al** [comment]
Thanks for the quick response, I am now ordering everything needed!
If the 3D case is not perfectly fit, I may modify it in the future.

**Comment by v1605** [comment]
No problem, the case should fit fine but any improvements are always welcome.
