### ISSUE TITLE
e-reader compatibility

### ISSUE THREAD

**Issue by msbeck** [v1605/open-source-cart-extender#2]
"Use this cart extender to increase the height of a gameboy cartriage and allow clearence for accessories that would not normally fit (Action Replay, boktai, E-Reader, etc...)."

Have you tested this with an e-reader on the analogue pocket?

**Comment by v1605** [comment]
I have not tested it we an e-reader. I've tested with an action replay (which boots to the menu but games don't load, probably due to the way the Pocket loads the games), regular cartridges, and it's been test on original hardware.

**Comment by msbeck** [comment]
Ok thanks. Have you tried it with Boktai?

**Comment by v1605** [comment]
Not me personally but it has been verified by other users. Eg. https://www.reddit.com/r/AnaloguePocket/comments/1bh4pfs/made_extra_cartridge_extenders_selling_the_extras/

**Comment by msbeck** [comment]
I made a bunch of these with professional solder work (i.e. not by my own hands) and listed them at my site https://aurbits.com/listing/1731831429/cart-extender-for-analogue-pocket-play e-reader works but not well.

**Comment by v1605** [comment]
Thanks for the update. Glad it work, even if not the most ideal. I would ask you to link the shell , not just mention the name of the project in the listing.

**Comment by msbeck** [comment]
Ok, I wasn't sure about external links on the listing because this is also listed on Etsy but I can try to add it and see if there's issues.
